---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
before_install:
  - 'eval $(curl https://travis-perl.github.io/init) --auto'
  - 'AUTHOR_TESTING=0 cpanm App::cpm'
  - 'AUTHOR_TESTING=0 cpm install --workers $(test-jobs) --global Code::TidyAll::Plugin::SortLines::Naturally Code::TidyAll::Plugin::UniqueLines Perl::Tidy'
cache:
  directories:
    - '~/perl5'
install:
  - 'AUTHOR_TESTING=0 cpm install --cpanfile cpanfile --workers $(test-jobs) --global'
language: perl
matrix:
  include:
    -
      env: COVERAGE=1
      perl: '5.26'
notifications:
  email:
    on_failure: always
    on_success: always
    recipients:
      - olaf@wundersolutions.com
perl:
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
  - '5.26'
script:
  - 'prove -lr -j$(test-jobs) t'
sudo: 'false'
